Repository Team14Contract/contractZZang, pull requests merged in 2023-09, with the labels that each got.

#8 [DESIGN] : 연락처 리스트 UI 제작
  .idea/inspectionProfiles/Project_Default.xml
  app/build.gradle
  app/src/main/res/drawable/ic_love_empty.png
  app/src/main/res/drawable/ic_love_filled.png
  app/src/main/res/drawable/img_profile.jpg
  app/src/main/res/layout/fragment_contract.xml
  app/src/main/res/layout/list_view_left.xml
  app/src/main/res/layout/list_view_right.xml
  app/src/main/res/values/colors.xml
Labels: design

#9 [DESIGN] : MyPage 제작
  .idea/gradle.xml
  .idea/misc.xml
  app/src/main/res/drawable/back.xml
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/shape2_mypage.xml
  app/src/main/res/drawable/shape3_mypage.xml
  app/src/main/res/drawable/shape_mypage.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: design

#14 CONFLICT: 병합 충돌 해결
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/res/drawable/account_plus.xml
  app/src/main/res/drawable/tab_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/style.xml
Labels: design

#15 [FEAT] : 연락처 리스트 recyclerView 제작
  app/src/main/java/com/example/contract/adapter/ContactItem.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
  app/src/main/res/layout/fragment_contract.xml
  app/src/main/res/layout/list_view_left.xml
Labels: feature

#22 [FEAT] : 연락처 리스트 Adapter 뷰 설정 제작
  app/src/main/java/com/example/contract/adapter/ContactItem.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
  app/src/main/res/layout/fragment_contract.xml
  app/src/main/res/layout/list_view_left.xml
  app/src/main/res/layout/list_view_right.xml
Labels: feature

#23 FEAT: AppBar 추가 및 기능 추가
  .idea/misc.xml
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/java/com/example/contract/fragment/ExitDialogFragment.kt
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_exit.xml
  app/src/main/res/menu/menu_list_type.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/style.xml
Labels: design, feature

#27 Feature/load contract
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/dialog_exit.xml
Labels: feature

#29 [FEAT] : 그리드 뷰 전환 제작
  .idea/deploymentTargetDropDown.xml
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
Labels: feature

#30 FIX: 데이터 구조 수정
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
  app/src/main/java/com/example/contract/sampledata/ContactManager.kt
Labels: fix

#35 [Feat]: ContactFragment에서 DetailActivity로 넘어가기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contract/DetailActivity.kt
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
  app/src/main/java/com/example/contract/sampledata/ContactItem.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/list_view_left.xml
Labels: feature

#36 [FEAT] 리스트 목록 스와이프 기능 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
  app/src/main/java/com/example/contract/fragment/CustomItemTouchHelper.kt
Labels: feature, fix

#37 [FEAT]:Detail Activity로 데이터 전달받기
  app/src/main/java/com/example/contract/DetailActivity.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
  app/src/main/java/com/example/contract/sampledata/ContactManager.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#38 [FEAT]:Detail Activity에서 문자와 전화 연결하기, MyPage에서 Edit기능 추가
  .idea/misc.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/contract/DetailActivity.kt
  app/src/main/java/com/example/contract/fragment/MyPageFragment.kt
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/custom_dialong.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: feature

#39 [FEAT]:Detail Activity과 ContactPage에서 하트버튼 누를시 채움하트로 바꾸기
  app/src/main/java/com/example/contract/DetailActivity.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/sampledata/ContactManager.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#42 DESIGN: MyPage UI 수정
  .idea/misc.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: design

#44 우리팀이 약속한 PR 타이틀
  README.md
Labels: design, feature

#48 [FEAT]:ContractPage에서 Favorite버튼 누를시 DetailPage도 채움하트로 변경
  app/src/main/java/com/example/contract/DetailActivity.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/sampledata/ContactItem.kt
  app/src/main/res/layout/activity_detail.xml
Labels: feature

#51 [DESIGN] : 전체적인 UI 디자인 수정
  app/src/main/res/drawable/shape3_mypage.xml
  app/src/main/res/drawable/shape_dialog_border.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/custom_dialong.xml
  app/src/main/res/layout/dialog_exit.xml
  app/src/main/res/layout/fragment_dialog.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: design

#52 Contact의 전체적인 이미지 적용 기능 개발
  .idea/misc.xml
  app/src/main/java/com/example/contract/DetailActivity.kt
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
  app/src/main/java/com/example/contract/fragment/DialogFragment.kt
  app/src/main/java/com/example/contract/sampledata/ContactItem.kt
  app/src/main/java/com/example/contract/sampledata/ContactManager.kt
Labels: feature, fix

#53 연락처 목록 복사 버그 수정
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/fragment/DialogFragment.kt
  app/src/main/java/com/example/contract/sampledata/ContactItem.kt
  app/src/main/java/com/example/contract/sampledata/ContactManager.kt
  app/src/main/res/drawable/ic_account.xml
Labels: bug

#55 리팩토링
  app/src/main/java/com/example/contract/DetailActivity.kt
  app/src/main/java/com/example/contract/MainActivity.kt
  app/src/main/java/com/example/contract/adapter/ListAdapter.kt
  app/src/main/java/com/example/contract/fragment/ContactFragment.kt
  app/src/main/java/com/example/contract/fragment/CustomItemTouchHelper.kt
  app/src/main/java/com/example/contract/fragment/DialogFragment.kt
  app/src/main/java/com/example/contract/fragment/ExitDialogFragment.kt
  app/src/main/java/com/example/contract/sampledata/ContactManager.kt
Labels: refactoring
